20201228 README 수정 제안 및 질문
samslow/ott-party pull request #1
Opened 2020-12-28 10:55 UTC by gmlwo530

이 브랜치는 delete 안 시키고 README 업데이트가 필요할 때 마다 쓰면 좋을 것 같습니다.

2020-12-28 10:55 UTC, gmlwo530 commented on README.md
> +   * 쿠팡 플레이?
?는 나중에 지원할 예정인거죠?

2020-12-28 10:55 UTC, gmlwo530 commented on README.md
>  4. 부가 기능
`부가 기능`은 MVP 달성 후 구현 해보면 좋을 기능이라고 해석 했는데 맞나요??!

2020-12-28 10:57 UTC, gmlwo530 commented on README.md
>     1. 푸시알람으로 문자 보내는 주기 알려주기
"계장이 설정 해놓은 OTT 결제일"에 계장에게 푸시 알림을 보내서, "계원들 입금 안 했으면 우리 서비스를 통해 입금 요청 문자 보내라"를 유도하는건가요?

2020-12-28 10:58 UTC, gmlwo530 commented on README.md
> +# 릴리즈 날짜
사이드 프로젝트긴 하지만 출시 목표는 있어야지 게을러지지 않을 것 같아서, 같이 논의해서 정하면 좋을듯!

2020-12-28 10:58 UTC, gmlwo530 commented on README.md
> +# 수익 구조(논의 중)
계속 생각해보면 좋을 듯 합니다

2020-12-29 09:30 UTC, samslow commented on README.md
> +   * 쿠팡 플레이?
넵 플랫폼 추가 자체는 어렵지 않아서 생각나는대로 다 적어봤어욤

2020-12-29 09:31 UTC, samslow commented on README.md
>  4. 부가 기능
넵 출시 후 시도할것입니다

2020-12-29 09:32 UTC, samslow commented on README.md
>     1. 푸시알람으로 문자 보내는 주기 알려주기
결제일에 푸시알람을 보내는 순간엔 아무도 입금을 안했을거라 입금 요청을 하라는 푸시를 보내는거고 
말씀하신건 미입금자에 대한 입금 요청인데 이건 추가기능으로 넣을만 하겠네용

2020-12-29 09:32 UTC, samslow commented on README.md
> +# 릴리즈 날짜
제 머릿속엔 1/3으로 생각하고 있긴 합니다.

2020-12-29 09:33 UTC, samslow commented on README.md
> +# 수익 구조(논의 중)
넵 일단은 앱 이용에 해가 가지 않게 하단 배너 광고만 넣어놓으려구요

2020-12-29 09:37 UTC, samslow requested changes

2020-12-29 09:37 UTC, samslow commented on README.md
> +      * PW 암호화 할 것이라는 것 고객들에게 어필 필요
좋은 의견!

2020-12-29 09:37 UTC, samslow commented on README.md
> +      * 휴대폰 번호를 추가하면 가입 여부 확인하고 문자로 초대 코드 보내주기
전 Flow를 최대한 간결하게 가져가려고 합니다. 가입이 필요하지 않았으면 해요.

2020-12-29 09:37 UTC, samslow commented on README.md
> +   4. 계원들 N월 입금 현황판
이건 MVP 에도 간단하게나마 들어가야 할듯하네요.

2020-12-29 09:37 UTC, samslow commented on README.md
> +   3. 계원들에게 보낸 문자 내역
이건 서비스 현황 페이지에서 하는게 나을듯 합니다.

2020-12-29 09:51 UTC, samslow commented
PR 올리고 저를 Reviewer로 등록해주시고 title은 commit이 되므로 prefix를 알맞게 써주시면 감사링

2020-12-29 10:55 UTC, gmlwo530 commented on README.md
>     1. 푸시알람으로 문자 보내는 주기 알려주기
아하 확인확인

2020-12-29 10:56 UTC, gmlwo530 commented on README.md
> +# 릴리즈 날짜
동의합니다

2020-12-29 10:57 UTC, gmlwo530 commented on README.md
> +   4. 계원들 N월 입금 현황판
4번은 넣어도 좋을듯..?!

2020-12-29 10:57 UTC, gmlwo530 commented on README.md
> +   3. 계원들에게 보낸 문자 내역
좋습니다

2020-12-29 11:00 UTC, gmlwo530 commented on README.md
> +      * 휴대폰 번호를 추가하면 가입 여부 확인하고 문자로 초대 코드 보내주기
혹시 `가입이 필요하지 않았으면 해요.`에서 `가입`이 회원 가입일까요?

2020-12-29 11:07 UTC, samslow commented on README.md
> +      * 휴대폰 번호를 추가하면 가입 여부 확인하고 문자로 초대 코드 보내주기
하아 이건 고민 포인트인데.. 카톡드림

2020-12-29 11:12 UTC, samslow approved these changes

2020-12-29 11:16 UTC, samslow approved these changes

2020-12-29 11:21 UTC, merged